[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-github"
  version = "43.0.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
